export const tourPackages = [
    { src: "/images/desertSafari.jpg", text: "Desert Safari" },
    { src: "/images/heliride.jpg", text: "Helicopter Ride" },
    { src: "/images/dowCuise.jpg", text: "Dhow Cruise Dinner" },
    { src: "/images/burjKhalifa.jpg", text: "Burj Khalifa Tour" },
    { src: "/images/dubaiCity.jpg", text: "Dubai City Tour" },
    { src: "/images/atlantas.jpg", text: "Atlantis Aquaventure" },
    { src: "/images/hotAir.jpg", text: "Hot Air Balloon Ride" },
    { src: "/images/marinaYacht.jpg", text: "Dubai Marina Yacht Cruise" },
    { src: "/images/garden.jpg", text: "Dubai Miracle Garden" },
    { src: "/images/dubai5.jpg", text: "Dubai Frame Experience" },
    { src: "/images/dubai1.jpg", text: "Ski Dubai Adventure" },
    { src: "/images/dubai2.jpg", text: "Ferrari World Tour" },
  ]
  
  export const topTours = [
    {
      src: "/images/desertSafari.jpg",
      price: 200,
      title: "Desert Safari",
      rating: 2,
      totalRatings: 4,
    },
    {
      src: "/images/heliride.jpg",
      price: 299.99,
      title: "Helicopter Ride",
      rating: 2,
      totalRatings: 148,
    },
    {
      src: "/images/dowCuise.jpg",
      price: 322,
      title: "Dhow Cruise Dinner",
      rating: 3.5,
      totalRatings: 234,
    },
    {
      src: "/images/burjKhalifa.jpg",
      price: 130,
      title: "Burj Khalifa Tour",
      rating: 5,
      totalRatings: 100,
    }, // Add totalRatings
    {
      src: "/images/dubaiCity.jpg",
      price: 180,
      title: "Dubai City Tour",
      rating: 4.5,
      totalRatings: 87,
    },
    {
      src: "/images/atlantas.jpg",
      price: 499.9,
      title: "Atlantis Aquaventure",
      rating: 4.5,
      totalRatings: 29,
    },
  ]
 
  export const topTours2 = [
    {
      src: "/images/hotAir.jpg",
      price: 250,
      title: "Hot Air Balloon Ride",
      rating: 4.8,
      totalRatings: 112,
    },
    {
      src: "/images/marinaYacht.jpg",
      price: 350,
      title: "Dubai Marina Yacht Cruise",
      rating: 4.7,
      totalRatings: 97,
    },
    {
      src: "/images/garden.jpg",
      price: 40,
      title: "Dubai Miracle Garden",
      rating: 4.3,
      totalRatings: 153,
    },
    {
      src: "/images/dubai5.jpg",
      price: 85,
      title: "Dubai Frame Experience",
      rating: 4.9,
      totalRatings: 89,
    },
    {
      src: "/images/dubai1.jpg",
      price: 300,
      title: "Ski Dubai Adventure",
      rating: 4.6,
      totalRatings: 74,
    },
    {
      src: "/images/dubai2.jpg",
      price: 450,
      title: "Ferrari World Tour",
      rating: 4.4,
      totalRatings: 65,
    },
  ]
  
  export const packagesData = [
    {
      src: "/images/desertSafari.jpg",
      title: "Desert Safari asdasdsa asdasd asdasd",
      price: 100,
      rating: 4.5,
      totalRatings: 150,
      time: 6,
      description: "Experience the thrill of a desert safari with dune bashing, camel rides, and traditional BBQ dinner Experience the thrill of a desert safari with dune bashing, camel rides, and traditional BBQ dinnerExperience the thrill of a desert safari with dune bashing, camel rides, and traditional BBQ dinnerExperience the thrill of a desert safari with dune bashing, camel rides, and traditional BBQ dinnerExperience the thrill of a desert safari with dune bashing, camel rides, and traditional BBQ dinner.",
    },
    {
      src: "/images/heliride.jpg",
      title: "Helicopter Ride",
      price: 300,
      rating: 4.8,
      totalRatings: 200,
      time: 1,
      description: "Enjoy breathtaking aerial views of Dubai on this unforgettable helicopter tour.",
    },
    {
      src: "/images/dowCuise.jpg",
      title: "Dhow Cruise Dinner",
      price: 80,
      rating: 4.2,
      totalRatings: 100,
      time: 2,
      description: "Sail along Dubai Creek while enjoying a delightful dinner and live entertainment.",
    },
    {
      src: "/images/burjKhalifa.jpg",
      title: "Burj Khalifa Tour",
      price: 150,
      rating: 4.6,
      totalRatings: 250,
      time: 2,
      description: "Visit the world's tallest building and enjoy panoramic views of the city.",
    },
    {
      src: "/images/dubaiCity.jpg",
      title: "Dubai City Tour",
      price: 70,
      rating: 4.4,
      totalRatings: 300,
      time: 4,
      description: "Explore the iconic landmarks of Dubai on this guided city tour.",
    },
    {
      src: "/images/atlantas.jpg",
      title: "Atlantis Aquaventure",
      price: 120,
      rating: 4.7,
      totalRatings: 180,
      time: 5,
      description: "Have a fun-filled day at Atlantis Aquaventure, one of the best water parks in the world.",
    },
    {
      src: "/images/hotAir.jpg",
      title: "Hot Air Balloon Ride",
      price: 250,
      rating: 4.9,
      totalRatings: 80,
      time: 1.5,
      description: "Take a magical hot air balloon ride over the stunning desert landscape.",
    },
    {
      src: "/images/marinaYacht.jpg",
      title: "Dubai Marina Yacht Cruise",
      price: 200,
      rating: 4.6,
      totalRatings: 160,
      time: 2,
      description: "Enjoy a luxurious yacht cruise around the beautiful Dubai Marina.",
    },
    {
      src: "/images/garden.jpg",
      title: "Dubai Miracle Garden",
      price: 50,
      rating: 4.5,
      totalRatings: 120,
      time: 3,
      description: "Visit the stunning Dubai Miracle Garden, home to over 45 million flowers.",
    },
    {
      src: "/images/dubai5.jpg",
      title: "Dubai Frame Experience",
      price: 90,
      rating: 4.3,
      totalRatings: 90,
      time: 1,
      description: "Experience the unique architecture of the Dubai Frame and enjoy spectacular views.",
    },
    {
      src: "/images/dubai1.jpg",
      title: "Ski Dubai Adventure",
      price: 110,
      rating: 4.8,
      totalRatings: 75,
      time: 2,
      description: "Experience skiing in the desert at Ski Dubai, the Middle East's first indoor ski resort.",
    },
    {
      src: "/images/dubai2.jpg",
      title: "Ferrari World Tour",
      price: 160,
      rating: 4.6,
      totalRatings: 110,
      time: 4,
      description: "Visit Ferrari World in Abu Dhabi for a day filled with thrilling rides and attractions.",
    },
  ];
  
  
  